[versions]
advrecyclerview = "1.0.0"
android = "3.0.1"
android-compileSdk = "37"
android-minSdk = "23"
android-targetSdk = "37"
android-buildTools = "37.0.0"


accompanistSwiperefresh = "0.36.0"
accompanistWebview = "0.36.0"
activity-compose = "1.10.1"
agp = "8.13.2"
androidx-constraintlayout = "2.2.1"
androidx-material = "1.12.0"
annotation = "1.9.1"
appUpdate = "2.1.0"
appcompat = "1.7.1"
circleimageview = "3.1.0"
coilCompose = "3.2.0"
coilNetworkKtor3 = "3.2.0"
compiler = "4.16.0"
compose-bom = "2025.06.01"
compose-compiler = "1.5.8"
core = "1.16.0"
core-ktx = "1.16.0"
datastore = "1.1.7"
espressoCore = "3.6.1"
firebase-bom = "33.16.0"
firebase-crashlytics-gradle = "3.0.4"
firebaseAds = "23.6.0"
firebaseAnalytics = "22.5.0"
firebaseCrashlytics = "19.4.4"
firebaseMessaging = "24.1.2"
google-services = "4.4.2"
hilt = "2.55"
hilt-navigation-compose = "1.2.0"
jsoup = "1.21.1"
junit = "4.13.2"
junitVersion = "1.2.1"
kotlin = "2.2.21"
ksp = "2.2.21-2.0.4"

#lifecycle = "2.9.1"
kotlinStdlibJdk8 = "2.2.21"
lifecycle = "2.8.7"

likebutton = "0.2.3"
lottie = "6.6.7"
material = "1.12.0"
multidex = "2.0.1"
navigation-compose = "2.9.1"
navigation = "2.9.1"
onesignal = "5.1.35"
playServicesAds = "24.4.0"
preference = "1.2.1"

preferenceVersion = "1.2.1"
review = "2.0.2"
room = "2.7.2"
roundedimageview = "2.3.0"
rules = "1.6.1"
swiperefreshlayout = "1.1.0"
transportApi = "4.0.0"


[libraries]
advrecyclerview = { module = "com.h6ah4i.android.widget.advrecyclerview:advrecyclerview", version.ref = "advrecyclerview" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycle" }
androidx-multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }
androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment", version.ref = "navigation" }
androidx-preference = { module = "androidx.preference:preference", version.ref = "preferenceVersion" }

androidx-rules = { module = "androidx.test:rules", version.ref = "rules" }
circleimageview = { module = "de.hdodenhof:circleimageview", version.ref = "circleimageview" }
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "compiler" }
firebase-ads = { module = "com.google.firebase:firebase-ads", version.ref = "firebaseAds" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "compiler" }
google-firebase-analytics = { module = "com.google.firebase:firebase-analytics", version.ref = "firebaseAnalytics" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlinStdlibJdk8" }
likebutton = { module = "com.github.jd-alexander:likebutton", version.ref = "likebutton" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
material = { group = "com.google.android.material", name = "material", version.ref = "androidx-material" }
play-services-ads = { group = "com.google.android.gms", name = "play-services-ads", version.ref = "playServicesAds" }

androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycle" }

jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
app-update = { module = "com.google.android.play:app-update", version.ref = "appUpdate" }
app-update-ktx = { module = "com.google.android.play:app-update-ktx", version.ref = "appUpdate" }
review = { module = "com.google.android.play:review", version.ref = "review" }
review-ktx = { module = "com.google.android.play:review-ktx", version.ref = "review" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preference"}
accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanistSwiperefresh" }
accompanist-webview = { module = "com.google.accompanist:accompanist-webview", version.ref = "accompanistWebview" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-material3 = { module = "androidx.compose.material3:material3" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-ui = { module = "androidx.compose.ui:ui" }
androidx-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
coil-network-ktor3 = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coilNetworkKtor3" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging", version.ref = "firebaseMessaging" }
google-firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics", version.ref = "firebaseCrashlytics" }
onesignal = { module = "com.onesignal:OneSignal", version.ref = "onesignal" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
androidx-lifecycle = { group = "androidx.lifecycle", name = "lifecycle", version.ref = "lifecycle" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coilCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-animation = { group = "androidx.compose.animation", name = "animation" }

androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation-compose" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt-navigation-compose" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }

firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }

androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
core = { module = "androidx.core:core", version.ref = "core" }
roundedimageview = { module = "com.makeramen:roundedimageview", version.ref = "roundedimageview" }
transport-api = { group = "com.google.android.datatransport", name = "transport-api", version.ref = "transportApi" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics-gradle" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }